# Generated by Django 3.2.1 on 2022-02-05 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('Nikon', 'Nikon'), ('Mobile', 'Mobile'), ('Fujiki', 'Fujiki'), ('GoPro', 'GoPro'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
