# Generated by Django 3.2.1 on 2022-02-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20220205_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='category',
            field=models.CharField(choices=[('mobile Review', 'mobile Review'), ('blog', 'blog'), ('comedy', 'comedy'), ('gamming', 'gamming'), ('flimmaking', 'flimmaking'), ('cooking', 'cooking'), ('food Blog', 'food Blog'), ('other', 'other')], max_length=255),
        ),
    ]
